name: Proof HTML
on:
  pull_request:
      branches:
        - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: anishathalye/proof-html@v1.1.0
        with:
          directory: ./
      - name: Sleep for 3 minutes
        uses: jakejarvis/wait-action@master
        with:
          time: '180s'
    
